-   id: clear-ipynb-cells
    name: Clear ipython notebooks cells.
    description: Clears the output of notebooks before committing.
    entry: clear-ipynb-cells
    language: python
    files: 'ipynb'

-   id: run-pycodestyle
    name: Run Pycodestyle.
    description: Runs pyQCA's pycodestyle. Can be configures in pyproject.toml
    entry: run-pycodestyle
    language: python
    files: 'py'

-   id: test-hook
    name: Test hook will auto-succeed.
    description: This test hook will print sys.argv and exit with code 0.
    entry: test-hook
    language: python