-   id: clear-ipynb-cells
    name: Clear ipython notebooks cells.
    description: Clears the output of notebooks before committing.
    entry: clear-ipynb-cells
    language: python
    files: 'ipynb'

-   id: run-pycodestyle
    name: Run PyCQA's pycodestyle against all *.py files.
    description: Runs pycodestyle. Can be configures in pyproject.toml
    entry: run-pycodestyle
    language: python
    files: 'py'

-   id: test-hook
    name: A test hook, that will always succeed.
    description: This test hook will print sys.argv and exit with code 0.
    entry: test-hook
    language: python