-   id: clear-ipynb-cells
    name: Clear ipython notebooks cells.
    description: Clears the output of notebooks before committing.
    entry: clear-ipynb-cells
    language: python
    files: 'ipynb'
