[tool.vulture]
paths = ['pre_commit_hooks']
ignore_decorators = ["@app.route", "@require_*"]
ignore_names = ["visit_*", "do_*"]
make_whitelist = true
min_confidence = 80
sort_by_size = true
verbose = true

[tool.run_pycodestyle]
verbose = true

[tool.run_coverage]
verbose = 3
testing = true